rootProject.name = "nova.api"
include("bootstrap")
include("core")
include("core-api")
include("query")
include("common")
include("web")
include("application")
include("application")
include("file-manager")
include("choices-write")
include("difficulties-write")
include("events-write")
include("games-write")
include("languages-write")
include("resources-write")
include("users-write")
