name: Test and deploy master

on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run gradlew test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test --stacktrace --scan
          wrapper-cache-enabled: true
          configuration-cache-enabled: true

  build-and-deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: novacloudregistry.azurecr.io
        username: ${{ secrets.acr_novacloudregistry_username }}
        password: ${{ secrets.acr_novacloudregistry_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/"  -f  "./docker/Dockerfile.cloud" -t novacloudregistry.azurecr.io/novacloudapi-img:${{ github.sha }}
        docker push novacloudregistry.azurecr.io/novacloudapi-img:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: nova-cloud-api
        app-settings-json: |
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "novacloudregistry.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.acr_novacloudregistry_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.acr_novacloudregistry_password }}",
              "slotSetting": false
            }
          ]

    - uses: azure/webapps-deploy@v2
      with:
        app-name: nova-cloud-api
        images: novacloudregistry.azurecr.io/novacloudapi-img:${{ github.sha }}
